- eclass/cargo.eclass
When instaling rust packages with Rust 1.42, it fails like the following message:
```
* Detected file collision(s):
*
*      /build/amd64-usr/usr/.crates2.json
```
Fix the install function in `cargo.eclass` so it can clean up the garbage json file.
> eclass: clean up .crates2.json when running cargo install

- acct-group/sshd/metadata.xml
- acct-group/sshd/sshd-0.ebuild
- acct-user/sshd/metadata.xml
- acct-user/sshd/sshd-0.ebuild
- eclass/acct-group.eclass
- eclass/acct-user.eclass
- eclass/user-info.eclass
- eclass/user.eclass
- metadata/md5-cache/acct-group/sshd-0
- metadata/md5-cache/acct-user/sshd-0
- metadata/md5-cache/virtual/libcrypt-1
- metadata/md5-cache/virtual/libcrypt-2
- profiles/categories
- virtual/libcrypt/libcrypt-1.ebuild
- virtual/libcrypt/libcrypt-2.ebuild
- virtual/libcrypt/metadata.xml
As dependencies needed by net-misc/openssh 8.1, add `acct-group/sshd`, `acct-user/sshd`, `virtual/libgcrypt`.
To do that, we need to add new categories, `acct-group` and `acct-user`.
Also we need to update eclasses like `user-info`, `user`, `acct-group`, `acct-user`.
> acct-*: add acct packages for openssh 8.1 for alpha

- acct-group/sshd/metadata.xml
- acct-group/sshd/sshd-0.ebuild
- acct-user/sshd/metadata.xml
- acct-user/sshd/sshd-0.ebuild
- eclass/acct-group.eclass
- eclass/acct-user.eclass
- eclass/user-info.eclass
- eclass/user.eclass
- metadata/md5-cache/acct-group/sshd-0
- metadata/md5-cache/acct-user/sshd-0
- metadata/md5-cache/virtual/libcrypt-1
- metadata/md5-cache/virtual/libcrypt-2
- profiles/categories
- virtual/libcrypt/libcrypt-1.ebuild
- virtual/libcrypt/libcrypt-2.ebuild
- virtual/libcrypt/metadata.xml
As dependencies needed by net-misc/openssh 8.1, add `acct-group/sshd`, `acct-user/sshd`, `virtual/libgcrypt`.
To do that, we need to add new categories, `acct-group` and `acct-user`.
Also we need to update eclasses like `user-info`, `user`, `acct-group`, `acct-user`.
> acct-*: add acct packages for openssh 8.1 for edge

- .github/workflows/rust-apply-patch.sh
- .github/workflows/rust-pull-request-alpha.yml
- .github/workflows/rust-pull-request-edge.yml
Whenever a new upstream Rust release appears, a Github workflow in `coreos-overlay` creates a new pull request for `dev-lang/rust`. At the same time, it sends a repository dispatch event to portage-stable, so it also creates a pull request for `virtual/rust`.
This PR should be merged together with https://github.com/flatcar-linux/coreos-overlay/pull/216 https://github.com/flatcar-linux/portage-stable/pull/44 https://github.com/flatcar-linux/portage-stable/pull/45.
> .github: add Github actions for virtual/rust

- dev-libs/libgcrypt/libgcrypt-1.8.4.ebuild
- dev-libs/libgcrypt/libgcrypt-1.8.5.ebuild
Get rid of garbage lines causing syntax errors when installing packages.
```
emerge-amd64-usr dev-libs/libgcrypt
```
> dev-libs/libgcrypt: fix syntax errors due to merge conflicts for edge

- eclass/linux-info.eclass
Kernel 5.8-rc2 or newer added a commit [f2f02ebd8f38](https://github.com/torvalds/linux/commit/f2f02ebd8f3833626642688b2d2c6a7b3c141fa9)
("kbuild: improve cc-option to clean up all temporary files") , which causes make commands to create an object output directory.
Apparently harmless.
The commit was backported to stable Kernels, 4.19.131, 5.4.50, 5.7.7.
In Flatcar and Gentoo, however, `getfilevar()` in `linux-info.eclass` runs a make command, which creates `${M}`, an object output directory, with a root account.
As Gentoo sandbox creates everything as non-root account, the subsequent steps like `src_unpack` fail to touch the same directory.
Upstream Gentoo already has a fix [5a3acd443c33](https://github.com/gentoo/gentoo/commit/5a3acd443c3347568d14d000776f46177317744a) …
> eclass: sync linux-info.eclass to fix Kernel build issues

- .github/workflows/rust-pull-request-main.yml
Improve body text of each PR for `virtual/rust`, by mentioning that it should be merged together with its paired PR in coreos-overlay.
Explicitly name `virtual/rust` instead of `Cargo`, because there is no more ebuild for `cargo`.
Rename the dispatched event-type name to `rust-pull-request-main`, as `cargo` has already disappeared.
Make the repository-dispatch action receive additional client-payload with a field `coreos-overlay-pull-request-number` sent by the corresponding PR in coreos-overlay.
The PR number is then used for adding a link in the body text, for pointing back to the PR in coreos-overlay.
This PR should be merged together with https://github.com/flatcar-linux/coreos-overlay/pull/575.
> .github: Improve body text of PR for virtual/rust

- acct-group/ntp/metadata.xml
- acct-group/ntp/ntp-0.ebuild
- acct-user/ntp/metadata.xml
- acct-user/ntp/ntp-0.ebuild
Add NTP group and user; required for updating NTP to gentoo upstream ntp-4.2.8_p15.
```
emerge-amd64-usr ntp
```
> acct-(group|user)/ntp: add NTP group and user

- eclass/toolchain-funcs.eclass
- net-dns/libidn2/libidn2-2.3.0.ebuild
- virtual/awk/awk-1.ebuild
- virtual/awk/metadata.xml
This PR contains a number of changes necessary to support glibc-2.32.
* add virtual/awk because of a new dependency by glibc
* update eclass/toolchain-funcs to latest upstream
* port libidn2-2.3.0 build recipe from EAPI7 to EAPI6 because our outdated portage doesn't handle BDEPEND well
> Ship changes necessary to update glibc to 2.32

- .github/workflows/rust-pull-request-main.yml
Github Actions for Rust started failing with following errors:
```
Error: Unable to process command '::set-env name=PULL_REQUEST_NUMBER::718' successfully.
Error: The `set-env` command is disabled. Please upgrade to using
Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`.
For more information see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
It happens because we have used `peter-evans/create-pull-request@v2`, which did not have a bug fix for the set-env issue.
The bug was fixed in create-pull-request [v3.4.1](https://github.com/peter-evans/create-pull-request/releases/tag/v3.4.1).
So we just need to update the version to `v3`, which already …
> .github: use create-pull-request@v3 to fix set-env issues

- scripts/bootstrap.sh
This change explicitly calls python3 (instead of python) in pycmd
so portage commands work (as we ship python 2, too, and it's still
the default).
Also, `static-libs` and `openmp` are added to the
bootstrap emerge USE flags (stage 3 of the bootstrap-sh script,
which is run in stage 2 of the SDK catalyst bootstrapping process):
- `static-libs` un-breaks the zlib build: zlib installed has this flag
set and zlib requested per emerge command line in
bootstrap.sh stage 3 needs this flag to prevent a slot conflict.
- `openmp` is to honour requirements of newer versions of GCC and is
added according to Gentoo guidelines published here:
https://wiki.gentoo.org/wiki/User:Sakaki/Sakaki%27s_EFI_Install_Guide/Building_the_Gentoo_Base_System_Minus_Kernel#Gentoo_Bootstrap_Remix:_Progressing_from_Stage_1 …
> SDK bootstrap related fixes in scripts/bootstrap: use python3; add static-libs, openmp

- sys-apps/gentoo-functions/gentoo-functions-0.13.ebuild
This one-line change pulls the gentoo-functions source tarball from
github instead from gentoo's own gitweb, to stabilise the build process.
We assume github to have higher availability than gentoo gitweb.
Signed-off-by: Thilo Fromm <thilo@kinvolk.io>
> sys-apps/gentoo-functions: use tarball from github

- app-misc/pax-utils/pax-utils-1.1.6.ebuild
- dev-libs/libev/libev-4.15-r1.ebuild
- dev-libs/libverto/libverto-0.2.5-r1.ebuild
- virtual/acl/acl-0-r1.ebuild
This PR is required to [upgrade glibc to 2.33](https://github.com/kinvolk/coreos-overlay/pull/1067) in coreos-overlay.
To un-break the toolchain build for arm64 for the glibc-2.33 update, a few packages require un-masking for arm64.
This change unmasks arm64 for
* app-misc/pax-utils
* dev-libs/libev, libverto
* virtual/acl
> Unmasks for arm64 required by glibc-2.33 upgrade

- eclass/go-module.eclass
Used in https://github.com/kinvolk/coreos-overlay/pull/1179
Image building and running the binaries went well in http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3249/cldsv/
> eclass: import go-module from Gentoo

- scripts/bootstrap.sh
Depclean failures in stage3 have been tracked down to stage1 containing openssl-1.1, and stage3 packages being built against that (dependencies are soft enough that they are not ordered against openssl-3 update in stage3). Add a workaround: explicitly build openssl-3 in stage2, right before stage3.
`./boostrap_sdk`.
CI will run.
> script/bootstrap: update openssl before stage3

- changelog/README.md
If we use date format of `DD-MM-YYYY` in changelog file names, the files will not sorted by date. e.g. `01-12-2021` will come before `25-11-2021`.
Use date format of `YYYY-MM-DD` to make the files sorted by date.
> changelog: use date format of YYYY-MM-DD

- changelog/security/2021-12-02-edk2-ovmf.md
Add missing changelog addressed by updating edk2-ovmf to [202105](https://github.com/flatcar-linux/portage-stable/pull/256).
- [CVE-2019-14584](https://nvd.nist.gov/vuln/detail/CVE-2019-14584)
- [CVE-2021-28210](https://nvd.nist.gov/vuln/detail/CVE-2021-28210)
- [CVE-2021-28211](https://nvd.nist.gov/vuln/detail/CVE-2021-28211)
- [CVE-2021-28213](https://nvd.nist.gov/vuln/detail/CVE-2021-28213)
> changelog: add changelog for edk2-ovmf 202105

- acct-group/portage/metadata.xml
- acct-group/portage/portage-0.ebuild
- acct-user/portage/metadata.xml
- acct-user/portage/portage-0.ebuild
Import `acct-user/portage` and `acct-group/portage` needed by `sys-apps/portage` 3.0.28.
This PR should be merged together with https://github.com/kinvolk/coreos-overlay/pull/1254.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4396/cldsv
> acct-{user,group}: import ebuilds for portage 3.0.28

- changelog/README.md
The changelog entries should be directly used for the release notes, thus they need to be short and hold only information relevant to the end user, and should be in the markdown bullet point format.
> changelog/README.md: describe purpose of the changelog entries

- eclass/systemd.eclass
Now EAPI <= 4 are gone, we can update this eclass.
Commit-Ref: 7b01b4e5c717e91eee103485209b12deb985adf3
Signed-off-by: Mathieu Tortuyaux <mtortuyaux@microsoft.com>
* CI(:large_blue_circle:): http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4643/cldsv/
Not user facing -> no changelog required.
> eclass: sync systemd

- eclass/alternatives.eclass
- eclass/mono-env.eclass
No big changes though, other than dropping support for old EAPIs.
CI: http://localhost:9091/job/os/job/manifest/4893/cldsv/
> Update eclasses from 2013

- changelog/changes/2022-03-22-fips.md
- sys-fs/cryptsetup/cryptsetup-2.3.6-r2.ebuild
- sys-fs/cryptsetup/metadata.xml
see https://github.com/flatcar-linux/coreos-overlay/pull/1778
[Done](http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5293/), failures seem unrelated
> Backport FIPS support for 3139

- changelog/changes/2022-03-22-fips.md
- sys-fs/cryptsetup/cryptsetup-2.4.3.ebuild
- sys-fs/cryptsetup/metadata.xml
see https://github.com/flatcar-linux/coreos-overlay/pull/1778
> Backport FIPS support for 3185

- changelog/README.md
To be able to distinguish changelog entries from each other, we should write a specific project name, e.g. `portage-stable`, instead of `PR`.
Changelog entries with a simple `PR` usually cause so much additional rework when doing actual releases.
> changelog: use a specific project name in the example

- eclass/edo.eclass
Import `edo.eclass` from Gentoo, as it is needed by `dev-libs/openssl` 3.0.3.
This PR should be merged together with https://github.com/flatcar-linux/coreos-overlay/pull/1898.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5651/cldsv/
-  Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update) (see https://github.com/flatcar-linux/coreos-overlay/pull/1898)
> eclass: import edo.eclass from Gentoo

- sec-policy/selinux-sssd/selinux-sssd-2.20200818-r2.ebuild
- sys-libs/liburing/files/liburing-2.1-gnu_source-musl-cpuset.patch
- sys-libs/liburing/liburing-2.1-r2.ebuild
This change bumps liburing-2.1 to upstream -rc2 and ingests a cross compiler fix (https://github.com/gentoo/gentoo/pull/24733).
Also, it removes the mask for ARM64 in sec-policy/selinux-sssd to match Gentoo upstream.
Build the image
```
./run_sdk_container -t 
./ build_packages --board=arm64-usr
./build_image --board=arm64-usr
./image_to_vm.sh ...
```
Launch the image
```
./flatcar_production_qemu_uefi.sh
[...]
core@localhost ~ $ sssd --version
2.3.1
```
Local arm64 test build succeeded, image boots, sssd prints version.
No changelog required since changelog entry will be added to PR in coreos-overlay.
> policy/sssd, libs/ding , liburing: add ARM64 support

- sec-policy/selinux-sssd/selinux-sssd-2.20200818-r2.ebuild
- sys-libs/liburing/files/liburing-2.1-gnu_source-musl-cpuset.patch
- sys-libs/liburing/liburing-2.1-r2.ebuild
Back-port / cherry-pick of https://github.com/flatcar-linux/portage-stable/pull/334 to flatcar-3227 for https://github.com/flatcar-linux/Flatcar/issues/775. Required by https://github.com/flatcar-linux/coreos-overlay/pull/1961 - see that PR for "how to use" / "Testing done".
This change bumps liburing-2.1 to upstream -rc2 and ingests a cross compiler fix (https://github.com/gentoo/gentoo/pull/24733).
Also, it removes the mask for ARM64 in sec-policy/selinux-sssd to match
Gentoo upstream.
> Backport to flatcar-3227: sec-policy/sssd, sys-libs/liburing: add ARM64 support

- .github/workflows/packages-list
- .github/workflows/update-packages-from-list.yml
It will run on every Monday and will try to update packages listed in the package listing. This can be used to gradually add more and more packages under the automation.
Ran on my own fork - added app-arch/zstd and sys-devel/gcc to the listing and run the workflow there. The resulting PR is here: https://github.com/krnowak/portage-stable/pull/2
> .github: Add an automatic package updates workflow

- .github/workflows/packages-list
- eclass/ltprune.eclass
- eclass/perl-functions.eclass
- eclass/wrapper.eclass
- sys-apps/iucode_tool/files/iucode_tool-2.3.1-limits-include.patch
- sys-apps/iucode_tool/iucode_tool-2.3.1-r1.ebuild
- sys-apps/iucode_tool/metadata.xml
- eclass/ltprune:
- doc fixes
- eclass/perl-functions:
- dropped support for old EAPI 5 and 6
- bash cosmetics
- ~eclass/selinux-policy-2:~
- ~contains my fix for patch applying~
- ~skips unconfined on MCS/MLS policy types~
- eclass/wrapper:
- dropped support for EAPIs older than 5
- has some weird trick for keeping the indentation intact
- sys-apps/iucode_tool:
- still at 2.3.1-r1
- adds some patch
There's nothing changeloggable.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/263/cldsv/
@tormath1 : I'm updating the selinux eclass here. If you prefer to keep it as is and update it as a part of your selinux update effort, please let me know - I'll drop it from the PR.
EDIT: Nevermind, dropped selinux eclass update - it caused some issues with selinux-virt package (an empty …
> Update pre-2021 stuff

- .github/workflows/update-packages-from-list.yml
Let's add date of today in the PR title, to avoid confusion when seeing the same title for multiple different weekly update PRs.
> .github: print date of today in the PR title

- .github/workflows/update-metadata-glsa.yml
- .github/workflows/update-packages-from-list.yml
Add a new monthly workflow `update-metadata-glsa`, to sync GLSA(Gentoo Linux Security Advisories) with upstream Gentoo.
While most individual metadata xml files are available on the upstream [mirror](https://github.com/gentoo-mirror/gentoo), its binary data as well as timestamp files do not exist on the public Git repo. So it is necessary to first rsync those data from `rsync.gentoo.org`, before actually running `sync-with-gentoo` script.
Remove unnecessary options in `update-packages-from-list`. As we already merged necessary changes for `sync-with-gentoo` into master branch of the flatcar-build-scripts repo, it is not necessary any more to point to `krnowak/stuff` branch. Remove it.
The checkout action of the Github Actions defaults to `fetch-depth=1`, when no fetch-depth is given. So …
> .github: add monthly workflow update-metadata-glsa

- .github/workflows/update-metadata-glsa.yml
Set a correct Author name and its email address to the commit message of monthly GLSA metadata PRs, `Flatcar Buildbot <buildbot@flatcar-linux.org>`.
> .github: set Author name to update-metadata-glsa

- scripts/bootstrap.sh
This fixes stage2 of the SDK build when catalyst in run in verbose mode.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/632/cldsv/
Also filed to upstream: https://github.com/gentoo/gentoo/pull/29612
> scripts/bootstrap: fix verbose bootstrap

- .github/workflows/update-packages-from-list.yml
Create a PR as a draft. Update the body to use a template that I usually use for package updates PRs. With these changes, stop counting the updated packages, as we don't use this info any more.
Tested on my fork. Also tried to make it to add the card to the project, but that is too much fuss.
> .github: Update package updates action
